// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeyftolnhfkydfzvntrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9leWZ0b2xuaGZreWRmenZudHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTMxMjYsImV4cCI6MjA2NTk2OTEyNn0.LUNZZigdy1wzFhX12GBaJwYNyP3Pd-gGn-kMR4P9iBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);